[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
zodiac_liquidity = "7qpT6gRLFm1F9kHLSkHpcMPM6sbdWRNokQaqae1Zz3j2"
zodiac_mixer = "H4zuwsksYGbfjpFjniuAXqf7ZK7HK854breBZLWgEo23"

[programs.localnet]
zodiac_liquidity = "7qpT6gRLFm1F9kHLSkHpcMPM6sbdWRNokQaqae1Zz3j2"
zodiac_mixer = "H4zuwsksYGbfjpFjniuAXqf7ZK7HK854breBZLWgEo23"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --exit \"tests/zodiac-mpc-meteora-integration.ts\""

[test]
startup_wait = 120000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"
program = "target/deploy/cp_amm.so"
