[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
zodiac_liquidity = "5iaJJzwRVTT47WLArixF8YoNJFMfLi8PTTmPRi9bdRGu"
zodiac_mixer = "ZMixer1111111111111111111111111111111111111"

[programs.localnet]
zodiac_liquidity = "5iaJJzwRVTT47WLArixF8YoNJFMfLi8PTTmPRi9bdRGu"
zodiac_mixer = "H4zuwsksYGbfjpFjniuAXqf7ZK7HK854breBZLWgEo23"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=c3913152-a27f-4ff6-b7ab-156bc13bb6e0"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 120000
shutdown_wait = 2000
upgradeable = false
